In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.3

Series = A pandas 1D labelled array that can hols any data.(Think of it as an single column in a spreadsheet[1 dimensional])

In [14]:
# We will use a list for a series here:
data = [100, 101, 102]
# Convert this list into series
series = pd.Series(data, index=["a","b","c"]) # Series is a contructor
series

a    100
b    101
c    102
dtype: int64

In [4]:
# To return a value from the label, we use the loc[] property:
print(series.loc["a"])

# To update a value using label we can use the loc[]:
series.loc["b"] = 98
print(series)
# So, the loc property essentially means "locating a value by label"

100
a    100
b     98
c    102
dtype: int64

In [5]:
# To locate by integer postion, we can use "iloc[]":
print(series.iloc[0])

# we need to get index starting from 0.
series.iloc[1] = 101
print(series)

100
a    100
b    101
c    102
dtype: int64

In [6]:
# To filter by value, we can use the subscript and then put some condition in it.
data2 = [100, 101, 102, 201, 202]
series2 = pd.Series(data2, index=["a","b","c","d","e"])
print(series2[series2 <= 200])

a    100
b    101
c    102
dtype: int64

In [7]:
# We will now use a dictionary for a series.
calories = {"day 1" : 1750, "day 2" : 2100, "day 3" : 1700}
# The major difference is that the key of the dictionary will become the label
series3 = pd.Series(calories)
print(series3)

day 1    1750
day 2    2100
day 3    1700
dtype: int64

In [8]:
#Here, we can use the loc property just like before. 
print(series3.loc["day 1"])

series3.loc["day 3"] += 175
print(series3.loc["day 3"])

print(series3[series3 >= 2000])

1750
1875
day 2    2100
dtype: int64

In [9]:
pokemons = ['bulbasaur' , 'Ivysaur' , 'Venasaur' , 'Charmander' , 'Charmeleon' , 'Charizard' ]
pd_series = pd.Series(pokemons , index=[1,2,3,4,5,6])
print(pd_series)

1     bulbasaur
2       Ivysaur
3      Venasaur
4    Charmander
5    Charmeleon
6     Charizard
dtype: str

Let's shift towards "DataFrames"  
DataFrames are a tabular data structure with 'Rows' AND 'Columns' (2 Dimensionsal). It is similar to an Excel Spreadsheet.

In [15]:
# We can create a DataFrame by using a Dictionary
data3 = {"Name" : ["Bob" , "Merlin", "Stacy", "Audrey", "Klein"],
         "Age" : [29, 25, 21, 20, 21]
        }
#Now we will convert the dictionary into a DataFrame by using pd.DataFrame.
df = pd.DataFrame(data3, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5"])

df

              Name  Age
Employee 1     Bob   29
Employee 2  Merlin   25
Employee 3   Stacy   21
Employee 4  Audrey   20
Employee 5   Klein   21

In [11]:
# We can use the loc property here as well.It still means locate by label.
# We can also use 'iloc[]' property as well.
print(df.loc["Employee 2"])
print(df.iloc[0])

Name    Merlin
Age         25
Name: Employee 2, dtype: object
Name    Bob
Age      29
Name: Employee 1, dtype: object

In [12]:
# To add a new column, we do it like this:
df["Job"] = ["Engineer", "Magician", "Receptionist", "Supervisor", "Student"]

df

              Name  Age           Job
Employee 1     Bob   29      Engineer
Employee 2  Merlin   25      Magician
Employee 3   Stacy   21  Receptionist
Employee 4  Audrey   20    Supervisor
Employee 5   Klein   21       Student

In [ ]:
# To add a new row, we can create a new DataFrame and then concatenate it.
# First, we will create a DataFrame which would be a list of dictionary, in which the 'key' would be the 'column_name' and the 'value' would be the new row value we want to add. We can also add the index for it as a label.

new_row = pd.DataFrame([{"Name": "Alger","Age" : 26 ,"Job": "Navy"}], index= ["Employee 6"])

# To add multiple rows, we can have different dictionaries in the list with the same format of "key","value" pairs seperated by commas, and for label, we can just add the new label seperated by comma in the list.

# new_row = pd.DataFrame([{"Name": "Alger","Age" : 26 ,"Job": "Navy"},
#                         {"Name: "Albert","Age" : 55 ,"Job": "Pilot"},
#                         {"Name: "Andy","Age" : 43 ,"Job": "Artist"}],
#                         index= ["Employee 6", "Employee 7", "Employee 8"])

# Now we will concatenate the two dataframes using 'pd.concat()':
df = pd.concat([df, new_row])

df

              Name  Age   Job
Employee 1     Bob   29   NaN
Employee 2  Merlin   25   NaN
Employee 3   Stacy   21   NaN
Employee 4  Audrey   20   NaN
Employee 5   Klein   21   NaN
Employee 6   Alger   26  Navy