In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.3

Series = A pandas 1D labelled array that can hols any data.(Think of it as an single column in a spreadsheet[1 dimensional])

In [3]:
# We will use a list for a series here:
data = [100, 101, 102]
# Convert this list into series
series = pd.Series(data, index=["a","b","c"]) # Series is a contructor
series

a    100
b    101
c    102
dtype: int64

In [4]:
# To return a value from the label, we use the loc[] property:
print(series.loc["a"])

# To update a value using label we can use the loc[]:
series.loc["b"] = 98
print(series)
# So, the loc property essentially means "locating a value by label"

100
a    100
b     98
c    102
dtype: int64

In [5]:
# To locate by integer postion, we can use "iloc[]":
print(series.iloc[0])

# we need to get index starting from 0.
series.iloc[1] = 101
print(series)

100
a    100
b    101
c    102
dtype: int64

In [6]:
# To filter by value, we can use the subscript and then put some condition in it.
data2 = [100, 101, 102, 201, 202]
series2 = pd.Series(data2, index=["a","b","c","d","e"])
print(series2[series2 <= 200])

a    100
b    101
c    102
dtype: int64

In [7]:
# We will now use a dictionary for a series.
calories = {"day 1" : 1750, "day 2" : 2100, "day 3" : 1700}
# The major difference is that the key of the dictionary will become the label
series3 = pd.Series(calories)
print(series3)

day 1    1750
day 2    2100
day 3    1700
dtype: int64

In [8]:
#Here, we can use the loc property just like before. 
print(series3.loc["day 1"])

series3.loc["day 3"] += 175
print(series3.loc["day 3"])

print(series3[series3 >= 2000])

1750
1875
day 2    2100
dtype: int64

In [9]:
pokemons = ['bulbasaur' , 'Ivysaur' , 'Venasaur' , 'Charmander' , 'Charmeleon' , 'Charizard' ]
pd_series = pd.Series(pokemons , index=[1,2,3,4,5,6])
print(pd_series)

1     bulbasaur
2       Ivysaur
3      Venasaur
4    Charmander
5    Charmeleon
6     Charizard
dtype: str

Let's shift towards "DataFrames"  
DataFrames are a tabular data structure with 'Rows' AND 'Columns' (2 Dimensionsal). It is similar to an Excel Spreadsheet.

In [10]:
# We can create a DataFrame by using a Dictionary
data3 = {"Name" : ["Bob" , "Merlin", "Stacy", "Audrey", "Klein"],
         "Age" : [29, 25, 21, 20, 21]
        }
#Now we will convert the dictionary into a DataFrame by using pd.DataFrame.
df = pd.DataFrame(data3, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5"])

df

              Name  Age
Employee 1     Bob   29
Employee 2  Merlin   25
Employee 3   Stacy   21
Employee 4  Audrey   20
Employee 5   Klein   21

In [11]:
# We can use the loc property here as well.It still means locate by label.
# We can also use 'iloc[]' property as well.
print(df.loc["Employee 2"])
print(df.iloc[0])

Name    Merlin
Age         25
Name: Employee 2, dtype: object
Name    Bob
Age      29
Name: Employee 1, dtype: object

In [12]:
# To add a new column, we do it like this:
df["Job"] = ["Engineer", "Magician", "Receptionist", "Supervisor", "Student"]

df

              Name  Age           Job
Employee 1     Bob   29      Engineer
Employee 2  Merlin   25      Magician
Employee 3   Stacy   21  Receptionist
Employee 4  Audrey   20    Supervisor
Employee 5   Klein   21       Student

In [13]:
# To add a new row, we can create a new DataFrame and then concatenate it.
# First, we will create a DataFrame which would be a list of dictionary, in which the 'key' would be the 'column_name' and the 'value' would be the new row value we want to add. We can also add the index for it as a label.

new_row = pd.DataFrame([{"Name": "Alger","Age" : 26 ,"Job": "Navy"}], index= ["Employee 6"])

# To add multiple rows, we can have different dictionaries in the list with the same format of "key","value" pairs seperated by commas, and for label, we can just add the new label seperated by comma in the list.

# new_row = pd.DataFrame([{"Name": "Alger","Age" : 26 ,"Job": "Navy"},
#                         {"Name: "Albert","Age" : 55 ,"Job": "Pilot"},
#                         {"Name: "Andy","Age" : 43 ,"Job": "Artist"}],
#                         index= ["Employee 6", "Employee 7", "Employee 8"])

# Now we will concatenate the two dataframes using 'pd.concat()':
df = pd.concat([df, new_row])

df

              Name  Age           Job
Employee 1     Bob   29      Engineer
Employee 2  Merlin   25      Magician
Employee 3   Stacy   21  Receptionist
Employee 4  Audrey   20    Supervisor
Employee 5   Klein   21       Student
Employee 6   Alger   26          Navy

Let us now work with importing.

In [14]:
# To read a csv file. we can use the read_csv() method
df1 = pd.read_csv("pokemon.csv")
df1

      No       Name    Type1   Type2  Height  Weight  Legendary
0      1  Bulbasaur    Grass  Poison     0.7     6.9          0
1      1  Bulbasaur    Grass  Poison     0.7     6.9          0
2      1  Bulbasaur    Grass  Poison     0.7     6.9          0
3      1  Bulbasaur    Grass  Poison     0.7     6.9          0
4      1  Bulbasaur    Grass  Poison     0.7     6.9          0
..   ...        ...      ...     ...     ...     ...        ...
152  149  Dragonite   Dragon  Flying     2.2   210.0          0
153  150     Mewtwo  Psychic     NaN     2.0   122.0          1
154  150     Mewtwo  Psychic     NaN     2.0   122.0          1
155  150     Mewtwo  Psychic     NaN     2.0   122.0          1
156  150     Mewtwo  Psychic     NaN     2.0   122.0          1

[157 rows x 7 columns]

In [15]:
# The above data is in the form truncated form. To get the whole data, we can use 'to_string()' method on the DataFrame. Note that when working with a great amount of data, the method would print literally all the data causing some performance issues. 
print(df1.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      1   Bulbasaur     Grass    Poison     0.7     6.9          0
2      1   Bulbasaur     Grass    Poison     0.7     6.9          0
3      1   Bulbasaur     Grass    Poison     0.7     6.9          0
4      1   Bulbasaur     Grass    Poison     0.7     6.9          0
5      2     Ivysaur     Grass    Poison     1.0    13.0          0
6      3    Venusaur     Grass    Poison     2.0   100.0          0
7      4  Charmander      Fire       NaN     0.6     8.5          0
8      5  Charmeleon      Fire       NaN     1.1    19.0          0
9      6   Charizard      Fire    Flying     1.7    90.5          0
10     7    Squirtle     Water       NaN     0.5     9.0          0
11     8   Wartortle     Water       NaN     1.0    22.5          0
12     9   Blastoise     Water       NaN     1.6    85.5          0
13    10    Caterpie       Bug       NaN     0.3     2.9          0
14    11     Metapod       Bug       NaN     0.7     9.9          0
15    12  Butterfree       Bug    Flying     1.1    32.0          0
16    13      Weedle       Bug    Poison     0.3     3.2          0
17    14      Kakuna       Bug    Poison     0.6    10.0          0
18    15    Beedrill       Bug    Poison     1.0    29.5          0
19    16      Pidgey    Normal    Flying     0.3     1.8          0
20    17   Pidgeotto    Normal    Flying     1.1    30.0          0
21    18     Pidgeot    Normal    Flying     1.5    39.5          0
22    19     Rattata    Normal       NaN     0.3     3.5          0
23    20    Raticate    Normal       NaN     0.7    18.5          0
24    21     Spearow    Normal    Flying     0.3     2.0          0
25    22      Fearow    Normal    Flying     1.2    38.0          0
26    23       Ekans    Poison       NaN     2.0     6.9          0
27    24       Arbok    Poison       NaN     3.5    65.0          0
28    25     Pikachu  Electric       NaN     0.4     6.0          0
29    26      Raichu  Electric       NaN     0.8    30.0          0
30    27   Sandshrew    Ground       NaN     0.6    12.0          0
31    28   Sandslash    Ground       NaN     1.0    29.5          0
32    29    Nidoran♀    Poison       NaN     0.4     7.0          0
33    30    Nidorina    Poison       NaN     0.8    20.0          0
34    31   Nidoqueen    Poison    Ground     1.3    60.0          0
35    32    Nidoran♂    Poison       NaN     0.5     9.0          0
36    33    Nidorino    Poison       NaN     0.9    19.5          0
37    34    Nidoking    Poison    Ground     1.4    62.0          0
38    35    Clefairy     Fairy       NaN     0.6     7.5          0
39    36    Clefable     Fairy       NaN     1.3    40.0          0
40    37      Vulpix      Fire       NaN     0.6     9.9          0
41    38   Ninetales      Fire       NaN     1.1    19.9          0
42    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
43    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
44    41       Zubat    Poison    Flying     0.8     7.5          0
45    42      Golbat    Poison    Flying     1.6    55.0          0
46    43      Oddish     Grass    Poison     0.5     5.4          0
47    44       Gloom     Grass    Poison     0.8     8.6          0
48    45   Vileplume     Grass    Poison     1.2    18.6          0
49    46       Paras       Bug     Grass     0.3     5.4          0
50    47    Parasect       Bug     Grass     1.0    29.5          0
51    48     Venonat       Bug    Poison     1.0    30.0          0
52    49    Venomoth       Bug    Poison     1.5    12.5          0
53    50     Diglett    Ground       NaN     0.2     0.8          0
54    51     Dugtrio    Ground       NaN     0.7    33.3          0
55    52      Meowth    Normal       NaN     0.4     4.2          0
56    53     Persian    Normal       NaN     1.0    32.0          0
57    54     Psyduck     Water       NaN     0.8    19.6          0
58    55     Golduck     Water       NaN     1.7    76.6          0
59    56      Mankey  Fighting       NaN     0.5    28.0          0
60    57    Primeape  Fighting       NaN     1.0    32.0          0
61    58   Growlithe      Fire       NaN     0.7    19.0          0
62    59    Arcanine      Fire       NaN     1.9   155.0          0
63    60     Poliwag     Water       NaN     0.6    12.4          0
64    61   Poliwhirl     Water       NaN     1.0    20.0          0
65    62   Poliwrath     Water  Fighting     1.3    54.0          0
66    63        Abra   Psychic       NaN     0.9    19.5          0
67    64     Kadabra   Psychic       NaN     1.3    56.5          0
68    65    Alakazam   Psychic       NaN     1.5    48.0          0
69    66      Machop  Fighting       NaN     0.8    19.5          0
70    67     Machoke  Fighting       NaN     1.5    70.5          0
71    68     Machamp  Fighting       NaN     1.6   130.0          0
72    69  Bellsprout     Grass    Poison     0.7     4.0          0
73    70  Weepinbell     Grass    Poison     1.0     6.4          0
74    71  Victreebel     Grass    Poison     1.7    15.5          0
75    72   Tentacool     Water    Poison     0.9    45.5          0
76    73  Tentacruel     Water    Poison     1.6    55.0          0
77    74     Geodude      Rock    Ground     0.4    20.0          0
78    75    Graveler      Rock    Ground     1.0   105.0          0
79    76       Golem      Rock    Ground     1.4   300.0          0
80    77      Ponyta      Fire       NaN     1.0    30.0          0
81    78    Rapidash      Fire       NaN     1.7    95.0          0
82    79    Slowpoke     Water   Psychic     1.2    36.0          0
83    80     Slowbro     Water   Psychic     1.6    78.5          0
84    81   Magnemite  Electric     Steel     0.3     6.0          0
85    82    Magneton  Electric     Steel     1.0    60.0          0
86    83  Farfetch'd    Normal    Flying     0.8    15.0          0
87    84       Doduo    Normal    Flying     1.4    39.2          0
88    85      Dodrio    Normal    Flying     1.8    85.2          0
89    86        Seel     Water       NaN     1.1    90.0          0
90    87     Dewgong     Water       Ice     1.7   120.0          0
91    88      Grimer    Poison       NaN     0.9    30.0          0
92    89         Muk    Poison       NaN     1.2    30.0          0
93    90    Shellder     Water       NaN     0.3     4.0          0
94    91    Cloyster     Water       Ice     1.5   132.5          0
95    92      Gastly     Ghost    Poison     1.3     0.1          0
96    93     Haunter     Ghost    Poison     1.6     0.1          0
97    94      Gengar     Ghost    Poison     1.5    40.5          0
98    95        Onix      Rock    Ground     8.8   210.0          0
99    96     Drowzee   Psychic       NaN     1.0    32.4          0
100   97       Hypno   Psychic       NaN     1.6    75.6          0
101   98      Krabby     Water       NaN     0.4     6.5          0
102   99     Kingler     Water       NaN     1.3    60.0          0
103  100     Voltorb  Electric       NaN     0.5    10.4          0
104  101   Electrode  Electric       NaN     1.2    66.6          0
105  102   Exeggcute     Grass   Psychic     0.4     2.5          0
106  103   Exeggutor     Grass   Psychic     2.0   120.0          0
107  104      Cubone    Ground       NaN     0.4     6.5          0
108  105     Marowak    Ground       NaN     1.0    45.0          0
109  106   Hitmonlee  Fighting       NaN     1.5    49.8          0
110  107  Hitmonchan  Fighting       NaN     1.4    50.2          0
111  108   Lickitung    Normal       NaN     1.2    65.5          0
112  109     Koffing    Poison       NaN     0.6     1.0          0
113  110     Weezing    Poison       NaN     1.2     9.5          0
114  111     Rhyhorn    Ground      Rock     1.0   115.0          0
115  112      Rhydon    Ground      Rock     1.9   120.0          0
116  113     Chansey    Normal       NaN     1.1    34.6          0
117  114     Tangela     Grass       NaN     1.0    35.0          0
118  115  Kangaskhan    Normal       NaN     2.2    80.0          0
119  116      Horsea     Water       NaN     0.4     8.0          0
120  117      Seadra     Water       NaN     1.2    25.0          0
121  118     Goldeen     Water       NaN     0.6    15.0          0
122  119     Seaking     Water       NaN     1.3    39.0          0
123  120      Staryu     Water       NaN     0.8    34.5          0
124  121     Starmie     Water   Psychic     1.1    80.0          0
125  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
126  123     Scyther       Bug    Flying     1.5    56.0          0
127  124        Jynx       Ice   Psychic     1.4    40.6          0
128  125  Electabuzz  Electric       NaN     1.1    30.0          0
129  126      Magmar      Fire       NaN     1.3    44.5          0
130  127      Pinsir       Bug       NaN     1.5    55.0          0
131  128      Tauros    Normal       NaN     1.4    88.4          0
132  129    Magikarp     Water       NaN     0.9    10.0          0
133  130    Gyarados     Water    Flying     6.5   235.0          0
134  131      Lapras     Water       Ice     2.5   220.0          0
135  132       Ditto    Normal       NaN     0.3     4.0          0
136  133       Eevee    Normal       NaN     0.3     6.5          0
137  134    Vaporeon     Water       NaN     1.0    29.0          0
138  135     Jolteon  Electric       NaN     0.8    24.5          0
139  136     Flareon      Fire       NaN     0.9    25.0          0
140  137     Porygon    Normal       NaN     0.8    36.5          0
141  138     Omanyte      Rock     Water     0.4     7.5          0
142  139     Omastar      Rock     Water     1.0    35.0          0
143  140      Kabuto      Rock     Water     0.5    11.5          0
144  141    Kabutops      Rock     Water     1.3    40.5          0
145  142  Aerodactyl      Rock    Flying     1.8    59.0          0
146  143     Snorlax    Normal       NaN     2.1   460.0          0
147  144    Articuno       Ice    Flying     1.7    55.4          1
148  145      Zapdos  Electric    Flying     1.6    52.6          1
149  146     Moltres      Fire    Flying     2.0    60.0          1
150  147     Dratini    Dragon       NaN     1.8     3.3          0
151  148   Dragonair    Dragon       NaN     4.0    16.5          0
152  149   Dragonite    Dragon    Flying     2.2   210.0          0
153  150      Mewtwo   Psychic       NaN     2.0   122.0          1
154  150      Mewtwo   Psychic       NaN     2.0   122.0          1
155  150      Mewtwo   Psychic       NaN     2.0   122.0          1
156  150      Mewtwo   Psychic       NaN     2.0   122.0          1

In [16]:
# We can use the 'read_json()' method to read a json file in the same way.
df2 = pd.read_json("pokemon.json")
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire               0.6     8.5          0
4      5  Charmeleon      Fire               1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water               0.5     9.0          0
7      8   Wartortle     Water               1.0    22.5          0
8      9   Blastoise     Water               1.6    85.5          0
9     10    Caterpie       Bug               0.3     2.9          0
10    11     Metapod       Bug               0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal               0.3     3.5          0
19    20    Raticate    Normal               0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison               2.0     6.9          0
23    24       Arbok    Poison               3.5    65.0          0
24    25     Pikachu  Electric               0.4     6.0          0
25    26      Raichu  Electric               0.8    30.0          0
26    27   Sandshrew    Ground               0.6    12.0          0
27    28   Sandslash    Ground               1.0    29.5          0
28    29    Nidoran♀    Poison               0.4     7.0          0
29    30    Nidorina    Poison               0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison               0.5     9.0          0
32    33    Nidorino    Poison               0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy               0.6     7.5          0
35    36    Clefable     Fairy               1.3    40.0          0
36    37      Vulpix      Fire               0.6     9.9          0
37    38   Ninetales      Fire               1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground               0.2     0.8          0
50    51     Dugtrio    Ground               0.7    33.3          0
51    52      Meowth    Normal               0.4     4.2          0
52    53     Persian    Normal               1.0    32.0          0
53    54     Psyduck     Water               0.8    19.6          0
54    55     Golduck     Water               1.7    76.6          0
55    56      Mankey  Fighting               0.5    28.0          0
56    57    Primeape  Fighting               1.0    32.0          0
57    58   Growlithe      Fire               0.7    19.0          0
58    59    Arcanine      Fire               1.9   155.0          0
59    60     Poliwag     Water               0.6    12.4          0
60    61   Poliwhirl     Water               1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic               0.9    19.5          0
63    64     Kadabra   Psychic               1.3    56.5          0
64    65    Alakazam   Psychic               1.5    48.0          0
65    66      Machop  Fighting               0.8    19.5          0
66    67     Machoke  Fighting               1.5    70.5          0
67    68     Machamp  Fighting               1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire               1.0    30.0          0
77    78    Rapidash      Fire               1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water               1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison               0.9    30.0          0
88    89         Muk    Poison               1.2    30.0          0
89    90    Shellder     Water               0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic               1.0    32.4          0
96    97       Hypno   Psychic               1.6    75.6          0
97    98      Krabby     Water               0.4     6.5          0
98    99     Kingler     Water               1.3    60.0          0
99   100     Voltorb  Electric               0.5    10.4          0
100  101   Electrode  Electric               1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground               0.4     6.5          0
104  105     Marowak    Ground               1.0    45.0          0
105  106   Hitmonlee  Fighting               1.5    49.8          0
106  107  Hitmonchan  Fighting               1.4    50.2          0
107  108   Lickitung    Normal               1.2    65.5          0
108  109     Koffing    Poison               0.6     1.0          0
109  110     Weezing    Poison               1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal               1.1    34.6          0
113  114     Tangela     Grass               1.0    35.0          0
114  115  Kangaskhan    Normal               2.2    80.0          0
115  116      Horsea     Water               0.4     8.0          0
116  117      Seadra     Water               1.2    25.0          0
117  118     Goldeen     Water               0.6    15.0          0
118  119     Seaking     Water               1.3    39.0          0
119  120      Staryu     Water               0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric               1.1    30.0          0
125  126      Magmar      Fire               1.3    44.5          0
126  127      Pinsir       Bug               1.5    55.0          0
127  128      Tauros    Normal               1.4    88.4          0
128  129    Magikarp     Water               0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal               0.3     4.0          0
132  133       Eevee    Normal               0.3     6.5          0
133  134    Vaporeon     Water               1.0    29.0          0
134  135     Jolteon  Electric               0.8    24.5          0
135  136     Flareon      Fire               0.9    25.0          0
136  137     Porygon    Normal               0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal               2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon               1.8     3.3          0
147  148   Dragonair    Dragon               4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic               2.0   122.0          1

Now let's see the different selection techniques in pandas.

In [17]:
# Selection By Column
print(df1["Name"].to_string())

0       Bulbasaur
1       Bulbasaur
2       Bulbasaur
3       Bulbasaur
4       Bulbasaur
5         Ivysaur
6        Venusaur
7      Charmander
8      Charmeleon
9       Charizard
10       Squirtle
11      Wartortle
12      Blastoise
13       Caterpie
14        Metapod
15     Butterfree
16         Weedle
17         Kakuna
18       Beedrill
19         Pidgey
20      Pidgeotto
21        Pidgeot
22        Rattata
23       Raticate
24        Spearow
25         Fearow
26          Ekans
27          Arbok
28        Pikachu
29         Raichu
30      Sandshrew
31      Sandslash
32       Nidoran♀
33       Nidorina
34      Nidoqueen
35       Nidoran♂
36       Nidorino
37       Nidoking
38       Clefairy
39       Clefable
40         Vulpix
41      Ninetales
42     Jigglypuff
43     Wigglytuff
44          Zubat
45         Golbat
46         Oddish
47          Gloom
48      Vileplume
49          Paras
50       Parasect
51        Venonat
52       Venomoth
53        Diglett
54        Dugtrio
55         Meowth
56        Persian
57        Psyduck
58        Golduck
59         Mankey
60       Primeape
61      Growlithe
62       Arcanine
63        Poliwag
64      Poliwhirl
65      Poliwrath
66           Abra
67        Kadabra
68       Alakazam
69         Machop
70        Machoke
71        Machamp
72     Bellsprout
73     Weepinbell
74     Victreebel
75      Tentacool
76     Tentacruel
77        Geodude
78       Graveler
79          Golem
80         Ponyta
81       Rapidash
82       Slowpoke
83        Slowbro
84      Magnemite
85       Magneton
86     Farfetch'd
87          Doduo
88         Dodrio
89           Seel
90        Dewgong
91         Grimer
92            Muk
93       Shellder
94       Cloyster
95         Gastly
96        Haunter
97         Gengar
98           Onix
99        Drowzee
100         Hypno
101        Krabby
102       Kingler
103       Voltorb
104     Electrode
105     Exeggcute
106     Exeggutor
107        Cubone
108       Marowak
109     Hitmonlee
110    Hitmonchan
111     Lickitung
112       Koffing
113       Weezing
114       Rhyhorn
115        Rhydon
116       Chansey
117       Tangela
118    Kangaskhan
119        Horsea
120        Seadra
121       Goldeen
122       Seaking
123        Staryu
124       Starmie
125      Mr. Mime
126       Scyther
127          Jynx
128    Electabuzz
129        Magmar
130        Pinsir
131        Tauros
132      Magikarp
133      Gyarados
134        Lapras
135         Ditto
136         Eevee
137      Vaporeon
138       Jolteon
139       Flareon
140       Porygon
141       Omanyte
142       Omastar
143        Kabuto
144      Kabutops
145    Aerodactyl
146       Snorlax
147      Articuno
148        Zapdos
149       Moltres
150       Dratini
151     Dragonair
152     Dragonite
153        Mewtwo
154        Mewtwo
155        Mewtwo
156        Mewtwo

In [18]:
# To select multiple columns, we can just pass a list:
print(df1[["Name", "Height", "Weight"]].to_string())

           Name  Height  Weight
0     Bulbasaur     0.7     6.9
1     Bulbasaur     0.7     6.9
2     Bulbasaur     0.7     6.9
3     Bulbasaur     0.7     6.9
4     Bulbasaur     0.7     6.9
5       Ivysaur     1.0    13.0
6      Venusaur     2.0   100.0
7    Charmander     0.6     8.5
8    Charmeleon     1.1    19.0
9     Charizard     1.7    90.5
10     Squirtle     0.5     9.0
11    Wartortle     1.0    22.5
12    Blastoise     1.6    85.5
13     Caterpie     0.3     2.9
14      Metapod     0.7     9.9
15   Butterfree     1.1    32.0
16       Weedle     0.3     3.2
17       Kakuna     0.6    10.0
18     Beedrill     1.0    29.5
19       Pidgey     0.3     1.8
20    Pidgeotto     1.1    30.0
21      Pidgeot     1.5    39.5
22      Rattata     0.3     3.5
23     Raticate     0.7    18.5
24      Spearow     0.3     2.0
25       Fearow     1.2    38.0
26        Ekans     2.0     6.9
27        Arbok     3.5    65.0
28      Pikachu     0.4     6.0
29       Raichu     0.8    30.0
30    Sandshrew     0.6    12.0
31    Sandslash     1.0    29.5
32     Nidoran♀     0.4     7.0
33     Nidorina     0.8    20.0
34    Nidoqueen     1.3    60.0
35     Nidoran♂     0.5     9.0
36     Nidorino     0.9    19.5
37     Nidoking     1.4    62.0
38     Clefairy     0.6     7.5
39     Clefable     1.3    40.0
40       Vulpix     0.6     9.9
41    Ninetales     1.1    19.9
42   Jigglypuff     0.5     5.5
43   Wigglytuff     1.0    12.0
44        Zubat     0.8     7.5
45       Golbat     1.6    55.0
46       Oddish     0.5     5.4
47        Gloom     0.8     8.6
48    Vileplume     1.2    18.6
49        Paras     0.3     5.4
50     Parasect     1.0    29.5
51      Venonat     1.0    30.0
52     Venomoth     1.5    12.5
53      Diglett     0.2     0.8
54      Dugtrio     0.7    33.3
55       Meowth     0.4     4.2
56      Persian     1.0    32.0
57      Psyduck     0.8    19.6
58      Golduck     1.7    76.6
59       Mankey     0.5    28.0
60     Primeape     1.0    32.0
61    Growlithe     0.7    19.0
62     Arcanine     1.9   155.0
63      Poliwag     0.6    12.4
64    Poliwhirl     1.0    20.0
65    Poliwrath     1.3    54.0
66         Abra     0.9    19.5
67      Kadabra     1.3    56.5
68     Alakazam     1.5    48.0
69       Machop     0.8    19.5
70      Machoke     1.5    70.5
71      Machamp     1.6   130.0
72   Bellsprout     0.7     4.0
73   Weepinbell     1.0     6.4
74   Victreebel     1.7    15.5
75    Tentacool     0.9    45.5
76   Tentacruel     1.6    55.0
77      Geodude     0.4    20.0
78     Graveler     1.0   105.0
79        Golem     1.4   300.0
80       Ponyta     1.0    30.0
81     Rapidash     1.7    95.0
82     Slowpoke     1.2    36.0
83      Slowbro     1.6    78.5
84    Magnemite     0.3     6.0
85     Magneton     1.0    60.0
86   Farfetch'd     0.8    15.0
87        Doduo     1.4    39.2
88       Dodrio     1.8    85.2
89         Seel     1.1    90.0
90      Dewgong     1.7   120.0
91       Grimer     0.9    30.0
92          Muk     1.2    30.0
93     Shellder     0.3     4.0
94     Cloyster     1.5   132.5
95       Gastly     1.3     0.1
96      Haunter     1.6     0.1
97       Gengar     1.5    40.5
98         Onix     8.8   210.0
99      Drowzee     1.0    32.4
100       Hypno     1.6    75.6
101      Krabby     0.4     6.5
102     Kingler     1.3    60.0
103     Voltorb     0.5    10.4
104   Electrode     1.2    66.6
105   Exeggcute     0.4     2.5
106   Exeggutor     2.0   120.0
107      Cubone     0.4     6.5
108     Marowak     1.0    45.0
109   Hitmonlee     1.5    49.8
110  Hitmonchan     1.4    50.2
111   Lickitung     1.2    65.5
112     Koffing     0.6     1.0
113     Weezing     1.2     9.5
114     Rhyhorn     1.0   115.0
115      Rhydon     1.9   120.0
116     Chansey     1.1    34.6
117     Tangela     1.0    35.0
118  Kangaskhan     2.2    80.0
119      Horsea     0.4     8.0
120      Seadra     1.2    25.0
121     Goldeen     0.6    15.0
122     Seaking     1.3    39.0
123      Staryu     0.8    34.5
124     Starmie     1.1    80.0
125    Mr. Mime     1.3    54.5
126     Scyther     1.5    56.0
127        Jynx     1.4    40.6
128  Electabuzz     1.1    30.0
129      Magmar     1.3    44.5
130      Pinsir     1.5    55.0
131      Tauros     1.4    88.4
132    Magikarp     0.9    10.0
133    Gyarados     6.5   235.0
134      Lapras     2.5   220.0
135       Ditto     0.3     4.0
136       Eevee     0.3     6.5
137    Vaporeon     1.0    29.0
138     Jolteon     0.8    24.5
139     Flareon     0.9    25.0
140     Porygon     0.8    36.5
141     Omanyte     0.4     7.5
142     Omastar     1.0    35.0
143      Kabuto     0.5    11.5
144    Kabutops     1.3    40.5
145  Aerodactyl     1.8    59.0
146     Snorlax     2.1   460.0
147    Articuno     1.7    55.4
148      Zapdos     1.6    52.6
149     Moltres     2.0    60.0
150     Dratini     1.8     3.3
151   Dragonair     4.0    16.5
152   Dragonite     2.2   210.0
153      Mewtwo     2.0   122.0
154      Mewtwo     2.0   122.0
155      Mewtwo     2.0   122.0
156      Mewtwo     2.0   122.0

In [19]:
# Selection by row can be done using the 'loc[]' method like: 
print(df1.loc[0])
print(df1.loc[1])

No                   1
Name         Bulbasaur
Type1            Grass
Type2           Poison
Height             0.7
Weight             6.9
Legendary            0
Name: 0, dtype: object
No                   1
Name         Bulbasaur
Type1            Grass
Type2           Poison
Height             0.7
Weight             6.9
Legendary            0
Name: 1, dtype: object

In [20]:
# It is quite hard to remember the default label of every pokemon that pandas has given, so we can just change the label into the name of the pokemon which is easy to look for. We can do that by using the 'index_col' and then entering the column we wnat to use as the index.

df3 = pd.read_csv("pokemon.csv" , index_col="Name")
df3

            No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1    Grass  Poison     0.7     6.9          0
Bulbasaur    1    Grass  Poison     0.7     6.9          0
Bulbasaur    1    Grass  Poison     0.7     6.9          0
Bulbasaur    1    Grass  Poison     0.7     6.9          0
Bulbasaur    1    Grass  Poison     0.7     6.9          0
...        ...      ...     ...     ...     ...        ...
Dragonite  149   Dragon  Flying     2.2   210.0          0
Mewtwo     150  Psychic     NaN     2.0   122.0          1
Mewtwo     150  Psychic     NaN     2.0   122.0          1
Mewtwo     150  Psychic     NaN     2.0   122.0          1
Mewtwo     150  Psychic     NaN     2.0   122.0          1

[157 rows x 6 columns]

In [21]:
# Now we can easily select a pokemon by the label i.e. Name
df3.loc["Pikachu"]
df3.loc["Charizard"]

No                6
Type1          Fire
Type2        Flying
Height          1.7
Weight         90.5
Legendary         0
Name: Charizard, dtype: object

In [22]:
# If we don't want all the data from the row, we can enter a tuple as an argument of all the columns that we want the data from.
print(df3.loc["Charizard", ("Height","Weight", "Legendary")])

Height        1.7
Weight       90.5
Legendary     0.0
Name: Charizard, dtype: float64

In [23]:
# We can also use slice operator (:) to get all the data between two values. For ex - 
print(df3.loc["Charizard" : "Pikachu", ("Height", "Weight")])

            Height  Weight
Name
Charizard      1.7    90.5
Squirtle       0.5     9.0
Wartortle      1.0    22.5
Blastoise      1.6    85.5
Caterpie       0.3     2.9
Metapod        0.7     9.9
Butterfree     1.1    32.0
Weedle         0.3     3.2
Kakuna         0.6    10.0
Beedrill       1.0    29.5
Pidgey         0.3     1.8
Pidgeotto      1.1    30.0
Pidgeot        1.5    39.5
Rattata        0.3     3.5
Raticate       0.7    18.5
Spearow        0.3     2.0
Fearow         1.2    38.0
Ekans          2.0     6.9
Arbok          3.5    65.0
Pikachu        0.4     6.0

In [24]:
# To get the first 10 rows with a step of two, we can use the 'iloc[]' property:
print(df3.iloc[0:11:2]) # The second number is excusive.

# we can also use other argument to select the amount of columns we need to show:
print(df3.iloc[0:11:2, 0:3])

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmeleon   5   Fire     NaN     1.1    19.0          0
Squirtle     7  Water     NaN     0.5     9.0          0
            No  Type1   Type2
Name
Bulbasaur    1  Grass  Poison
Bulbasaur    1  Grass  Poison
Bulbasaur    1  Grass  Poison
Venusaur     3  Grass  Poison
Charmeleon   5   Fire     NaN
Squirtle     7  Water     NaN

Now, let us proceed to Filtering

Filtering means keeping the rows that match a certain condition.

In [25]:
dataf = pd.read_csv("pokemon.csv")

#Lets say we want to filter the dataframe by the some height of the pokemons, then we can just do this:
tall_pokemon = dataf[dataf["Height"] >= 2]

# If we want to check for two conditions, we can use OR/AND operators on different conditions in paratheses.
water_pokemon = dataf[(dataf["Type1"] == "Water") | (dataf["Type2"] == "Water")]
ff_pokemon = dataf[(dataf["Type1"] == "Fire") & (dataf["Type2"] == "Flying")]
print(tall_pokemon)
print(" ")
print(water_pokemon)
print(" ")
print(ff_pokemon)

      No        Name    Type1    Type2  Height  Weight  Legendary
6      3    Venusaur    Grass   Poison     2.0   100.0          0
26    23       Ekans   Poison      NaN     2.0     6.9          0
27    24       Arbok   Poison      NaN     3.5    65.0          0
98    95        Onix     Rock   Ground     8.8   210.0          0
106  103   Exeggutor    Grass  Psychic     2.0   120.0          0
118  115  Kangaskhan   Normal      NaN     2.2    80.0          0
133  130    Gyarados    Water   Flying     6.5   235.0          0
134  131      Lapras    Water      Ice     2.5   220.0          0
146  143     Snorlax   Normal      NaN     2.1   460.0          0
149  146     Moltres     Fire   Flying     2.0    60.0          1
151  148   Dragonair   Dragon      NaN     4.0    16.5          0
152  149   Dragonite   Dragon   Flying     2.2   210.0          0
153  150      Mewtwo  Psychic      NaN     2.0   122.0          1
154  150      Mewtwo  Psychic      NaN     2.0   122.0          1
155  150      Mewtwo  Psychic      NaN     2.0   122.0          1
156  150      Mewtwo  Psychic      NaN     2.0   122.0          1

      No        Name  Type1     Type2  Height  Weight  Legendary
10     7    Squirtle  Water       NaN     0.5     9.0          0
11     8   Wartortle  Water       NaN     1.0    22.5          0
12     9   Blastoise  Water       NaN     1.6    85.5          0
57    54     Psyduck  Water       NaN     0.8    19.6          0
58    55     Golduck  Water       NaN     1.7    76.6          0
63    60     Poliwag  Water       NaN     0.6    12.4          0
64    61   Poliwhirl  Water       NaN     1.0    20.0          0
65    62   Poliwrath  Water  Fighting     1.3    54.0          0
75    72   Tentacool  Water    Poison     0.9    45.5          0
76    73  Tentacruel  Water    Poison     1.6    55.0          0
82    79    Slowpoke  Water   Psychic     1.2    36.0          0
83    80     Slowbro  Water   Psychic     1.6    78.5          0
89    86        Seel  Water       NaN     1.1    90.0          0
90    87     Dewgong  Water       Ice     1.7   120.0          0
93    90    Shellder  Water       NaN     0.3     4.0          0
94    91    Cloyster  Water       Ice     1.5   132.5          0
101   98      Krabby  Water       NaN     0.4     6.5          0
102   99     Kingler  Water       NaN     1.3    60.0          0
119  116      Horsea  Water       NaN     0.4     8.0          0
120  117      Seadra  Water       NaN     1.2    25.0          0
121  118     Goldeen  Water       NaN     0.6    15.0          0
122  119     Seaking  Water       NaN     1.3    39.0          0
123  120      Staryu  Water       NaN     0.8    34.5          0
124  121     Starmie  Water   Psychic     1.1    80.0          0
132  129    Magikarp  Water       NaN     0.9    10.0          0
133  130    Gyarados  Water    Flying     6.5   235.0          0
134  131      Lapras  Water       Ice     2.5   220.0          0
137  134    Vaporeon  Water       NaN     1.0    29.0          0
141  138     Omanyte   Rock     Water     0.4     7.5          0
142  139     Omastar   Rock     Water     1.0    35.0          0
143  140      Kabuto   Rock     Water     0.5    11.5          0
144  141    Kabutops   Rock     Water     1.3    40.5          0

      No       Name Type1   Type2  Height  Weight  Legendary
9      6  Charizard  Fire  Flying     1.7    90.5          0
149  146    Moltres  Fire  Flying     2.0    60.0          1

Now let us go through aggregate functions.  
***aggregate functions*** - Reduces a set of values into a single summary value. Used to summarize and analyze data.  
Often used by __groupby()__ function.

In [26]:
# For finding the mean of data, we can use the mean() aggregate function. In order to only find use the numeric value for mean, we give an argument of 'numeric_only = True'.

print(dataf.mean(numeric_only=True))

No           75.025478
Height        1.202548
Weight       46.677070
Legendary     0.044586
dtype: float64

In [27]:
# using sum() aggregate fumction
print(dataf.sum(numeric_only=True))

No           11779.0
Height         188.8
Weight        7328.3
Legendary        7.0
dtype: float64

In [28]:
# using min() aggregate function
print(dataf.min(numeric_only=True))

No           1.0
Height       0.2
Weight       0.1
Legendary    0.0
dtype: float64

In [29]:
# using max() aggregate function
print(dataf.max(numeric_only=True))

No           150.0
Height         8.8
Weight       460.0
Legendary      1.0
dtype: float64

In [30]:
# using count() aggregate function
print(dataf.count())

No           157
Name         157
Type1        157
Type2         71
Height       157
Weight       157
Legendary    157
dtype: int64

Now comes the aggregate functions that can be applied to a single column

In [31]:
print(dataf["Height"].mean())
print(dataf["Height"].sum())
print(dataf["Height"].min())
print(dataf["Height"].max())
print(dataf["Height"].count())

1.2025477707006371
188.8
0.2
8.8
157

Now, we can group the data in DataFrame by some specific column using the **groupby()** function.   
We can then use the **aggregate function** on this group to get more specific information about the grouped column type data.

In [32]:
group = dataf.groupby("Type1")
print(group["Height"].mean())

Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       0.987500
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.560000
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

In [33]:
print(group["Height"].sum())

Type1
Bug         10.8
Dragon       8.0
Electric     7.7
Fairy        1.9
Fighting     8.3
Fire        14.6
Ghost        4.4
Grass       15.8
Ground       6.8
Ice          3.1
Normal      21.7
Poison      17.1
Psychic     15.6
Rock        16.6
Water       36.4
Name: Height, dtype: float64

This is how we can go on with aggregate functions for groupby() function.

Let's now roll with Data cleaning using Pandas.  
Data cleaning is removing/fixing any irrelevant, incomplete, incorrect data. ~75% of Data cleaning is done in pandas

In [34]:
# 1. Drop irrelevant columns
# We can use 'drop(columns=[])' to drop the columns. just need to enter the columns in the list.
dataf = dataf.drop(columns=["Legendary"]) # This functions assigns a new DataFrame, so we need to reassign it there.
dataf

      No       Name    Type1   Type2  Height  Weight
0      1  Bulbasaur    Grass  Poison     0.7     6.9
1      1  Bulbasaur    Grass  Poison     0.7     6.9
2      1  Bulbasaur    Grass  Poison     0.7     6.9
3      1  Bulbasaur    Grass  Poison     0.7     6.9
4      1  Bulbasaur    Grass  Poison     0.7     6.9
..   ...        ...      ...     ...     ...     ...
152  149  Dragonite   Dragon  Flying     2.2   210.0
153  150     Mewtwo  Psychic     NaN     2.0   122.0
154  150     Mewtwo  Psychic     NaN     2.0   122.0
155  150     Mewtwo  Psychic     NaN     2.0   122.0
156  150     Mewtwo  Psychic     NaN     2.0   122.0

[157 rows x 6 columns]

In [35]:
# 2. Handling Missing data
# In the data, There were some pokemons which didn't have any Type2. If we have to remove those pokemons:
datafq = dataf.dropna(subset=["Type2"])
datafq

      No        Name     Type1   Type2  Height  Weight
0      1   Bulbasaur     Grass  Poison     0.7     6.9
1      1   Bulbasaur     Grass  Poison     0.7     6.9
2      1   Bulbasaur     Grass  Poison     0.7     6.9
3      1   Bulbasaur     Grass  Poison     0.7     6.9
4      1   Bulbasaur     Grass  Poison     0.7     6.9
..   ...         ...       ...     ...     ...     ...
145  142  Aerodactyl      Rock  Flying     1.8    59.0
147  144    Articuno       Ice  Flying     1.7    55.4
148  145      Zapdos  Electric  Flying     1.6    52.6
149  146     Moltres      Fire  Flying     2.0    60.0
152  149   Dragonite    Dragon  Flying     2.2   210.0

[71 rows x 6 columns]

In [36]:
# If we don't want to remove the missing values but instead fill them:
dataf = dataf.fillna({"Type2" : "None"}) # We are replacing NaN values with 'None' in Type2 column
print(dataf.to_string())

      No        Name     Type1     Type2  Height  Weight
0      1   Bulbasaur     Grass    Poison     0.7     6.9
1      1   Bulbasaur     Grass    Poison     0.7     6.9
2      1   Bulbasaur     Grass    Poison     0.7     6.9
3      1   Bulbasaur     Grass    Poison     0.7     6.9
4      1   Bulbasaur     Grass    Poison     0.7     6.9
5      2     Ivysaur     Grass    Poison     1.0    13.0
6      3    Venusaur     Grass    Poison     2.0   100.0
7      4  Charmander      Fire      None     0.6     8.5
8      5  Charmeleon      Fire      None     1.1    19.0
9      6   Charizard      Fire    Flying     1.7    90.5
10     7    Squirtle     Water      None     0.5     9.0
11     8   Wartortle     Water      None     1.0    22.5
12     9   Blastoise     Water      None     1.6    85.5
13    10    Caterpie       Bug      None     0.3     2.9
14    11     Metapod       Bug      None     0.7     9.9
15    12  Butterfree       Bug    Flying     1.1    32.0
16    13      Weedle       Bug    Poison     0.3     3.2
17    14      Kakuna       Bug    Poison     0.6    10.0
18    15    Beedrill       Bug    Poison     1.0    29.5
19    16      Pidgey    Normal    Flying     0.3     1.8
20    17   Pidgeotto    Normal    Flying     1.1    30.0
21    18     Pidgeot    Normal    Flying     1.5    39.5
22    19     Rattata    Normal      None     0.3     3.5
23    20    Raticate    Normal      None     0.7    18.5
24    21     Spearow    Normal    Flying     0.3     2.0
25    22      Fearow    Normal    Flying     1.2    38.0
26    23       Ekans    Poison      None     2.0     6.9
27    24       Arbok    Poison      None     3.5    65.0
28    25     Pikachu  Electric      None     0.4     6.0
29    26      Raichu  Electric      None     0.8    30.0
30    27   Sandshrew    Ground      None     0.6    12.0
31    28   Sandslash    Ground      None     1.0    29.5
32    29    Nidoran♀    Poison      None     0.4     7.0
33    30    Nidorina    Poison      None     0.8    20.0
34    31   Nidoqueen    Poison    Ground     1.3    60.0
35    32    Nidoran♂    Poison      None     0.5     9.0
36    33    Nidorino    Poison      None     0.9    19.5
37    34    Nidoking    Poison    Ground     1.4    62.0
38    35    Clefairy     Fairy      None     0.6     7.5
39    36    Clefable     Fairy      None     1.3    40.0
40    37      Vulpix      Fire      None     0.6     9.9
41    38   Ninetales      Fire      None     1.1    19.9
42    39  Jigglypuff    Normal     Fairy     0.5     5.5
43    40  Wigglytuff    Normal     Fairy     1.0    12.0
44    41       Zubat    Poison    Flying     0.8     7.5
45    42      Golbat    Poison    Flying     1.6    55.0
46    43      Oddish     Grass    Poison     0.5     5.4
47    44       Gloom     Grass    Poison     0.8     8.6
48    45   Vileplume     Grass    Poison     1.2    18.6
49    46       Paras       Bug     Grass     0.3     5.4
50    47    Parasect       Bug     Grass     1.0    29.5
51    48     Venonat       Bug    Poison     1.0    30.0
52    49    Venomoth       Bug    Poison     1.5    12.5
53    50     Diglett    Ground      None     0.2     0.8
54    51     Dugtrio    Ground      None     0.7    33.3
55    52      Meowth    Normal      None     0.4     4.2
56    53     Persian    Normal      None     1.0    32.0
57    54     Psyduck     Water      None     0.8    19.6
58    55     Golduck     Water      None     1.7    76.6
59    56      Mankey  Fighting      None     0.5    28.0
60    57    Primeape  Fighting      None     1.0    32.0
61    58   Growlithe      Fire      None     0.7    19.0
62    59    Arcanine      Fire      None     1.9   155.0
63    60     Poliwag     Water      None     0.6    12.4
64    61   Poliwhirl     Water      None     1.0    20.0
65    62   Poliwrath     Water  Fighting     1.3    54.0
66    63        Abra   Psychic      None     0.9    19.5
67    64     Kadabra   Psychic      None     1.3    56.5
68    65    Alakazam   Psychic      None     1.5    48.0
69    66      Machop  Fighting      None     0.8    19.5
70    67     Machoke  Fighting      None     1.5    70.5
71    68     Machamp  Fighting      None     1.6   130.0
72    69  Bellsprout     Grass    Poison     0.7     4.0
73    70  Weepinbell     Grass    Poison     1.0     6.4
74    71  Victreebel     Grass    Poison     1.7    15.5
75    72   Tentacool     Water    Poison     0.9    45.5
76    73  Tentacruel     Water    Poison     1.6    55.0
77    74     Geodude      Rock    Ground     0.4    20.0
78    75    Graveler      Rock    Ground     1.0   105.0
79    76       Golem      Rock    Ground     1.4   300.0
80    77      Ponyta      Fire      None     1.0    30.0
81    78    Rapidash      Fire      None     1.7    95.0
82    79    Slowpoke     Water   Psychic     1.2    36.0
83    80     Slowbro     Water   Psychic     1.6    78.5
84    81   Magnemite  Electric     Steel     0.3     6.0
85    82    Magneton  Electric     Steel     1.0    60.0
86    83  Farfetch'd    Normal    Flying     0.8    15.0
87    84       Doduo    Normal    Flying     1.4    39.2
88    85      Dodrio    Normal    Flying     1.8    85.2
89    86        Seel     Water      None     1.1    90.0
90    87     Dewgong     Water       Ice     1.7   120.0
91    88      Grimer    Poison      None     0.9    30.0
92    89         Muk    Poison      None     1.2    30.0
93    90    Shellder     Water      None     0.3     4.0
94    91    Cloyster     Water       Ice     1.5   132.5
95    92      Gastly     Ghost    Poison     1.3     0.1
96    93     Haunter     Ghost    Poison     1.6     0.1
97    94      Gengar     Ghost    Poison     1.5    40.5
98    95        Onix      Rock    Ground     8.8   210.0
99    96     Drowzee   Psychic      None     1.0    32.4
100   97       Hypno   Psychic      None     1.6    75.6
101   98      Krabby     Water      None     0.4     6.5
102   99     Kingler     Water      None     1.3    60.0
103  100     Voltorb  Electric      None     0.5    10.4
104  101   Electrode  Electric      None     1.2    66.6
105  102   Exeggcute     Grass   Psychic     0.4     2.5
106  103   Exeggutor     Grass   Psychic     2.0   120.0
107  104      Cubone    Ground      None     0.4     6.5
108  105     Marowak    Ground      None     1.0    45.0
109  106   Hitmonlee  Fighting      None     1.5    49.8
110  107  Hitmonchan  Fighting      None     1.4    50.2
111  108   Lickitung    Normal      None     1.2    65.5
112  109     Koffing    Poison      None     0.6     1.0
113  110     Weezing    Poison      None     1.2     9.5
114  111     Rhyhorn    Ground      Rock     1.0   115.0
115  112      Rhydon    Ground      Rock     1.9   120.0
116  113     Chansey    Normal      None     1.1    34.6
117  114     Tangela     Grass      None     1.0    35.0
118  115  Kangaskhan    Normal      None     2.2    80.0
119  116      Horsea     Water      None     0.4     8.0
120  117      Seadra     Water      None     1.2    25.0
121  118     Goldeen     Water      None     0.6    15.0
122  119     Seaking     Water      None     1.3    39.0
123  120      Staryu     Water      None     0.8    34.5
124  121     Starmie     Water   Psychic     1.1    80.0
125  122    Mr. Mime   Psychic     Fairy     1.3    54.5
126  123     Scyther       Bug    Flying     1.5    56.0
127  124        Jynx       Ice   Psychic     1.4    40.6
128  125  Electabuzz  Electric      None     1.1    30.0
129  126      Magmar      Fire      None     1.3    44.5
130  127      Pinsir       Bug      None     1.5    55.0
131  128      Tauros    Normal      None     1.4    88.4
132  129    Magikarp     Water      None     0.9    10.0
133  130    Gyarados     Water    Flying     6.5   235.0
134  131      Lapras     Water       Ice     2.5   220.0
135  132       Ditto    Normal      None     0.3     4.0
136  133       Eevee    Normal      None     0.3     6.5
137  134    Vaporeon     Water      None     1.0    29.0
138  135     Jolteon  Electric      None     0.8    24.5
139  136     Flareon      Fire      None     0.9    25.0
140  137     Porygon    Normal      None     0.8    36.5
141  138     Omanyte      Rock     Water     0.4     7.5
142  139     Omastar      Rock     Water     1.0    35.0
143  140      Kabuto      Rock     Water     0.5    11.5
144  141    Kabutops      Rock     Water     1.3    40.5
145  142  Aerodactyl      Rock    Flying     1.8    59.0
146  143     Snorlax    Normal      None     2.1   460.0
147  144    Articuno       Ice    Flying     1.7    55.4
148  145      Zapdos  Electric    Flying     1.6    52.6
149  146     Moltres      Fire    Flying     2.0    60.0
150  147     Dratini    Dragon      None     1.8     3.3
151  148   Dragonair    Dragon      None     4.0    16.5
152  149   Dragonite    Dragon    Flying     2.2   210.0
153  150      Mewtwo   Psychic      None     2.0   122.0
154  150      Mewtwo   Psychic      None     2.0   122.0
155  150      Mewtwo   Psychic      None     2.0   122.0
156  150      Mewtwo   Psychic      None     2.0   122.0

In [37]:
# 3. Fix inconsistent values.
# In order to fix inconsistent values, we can use .replace({"x" : "X"}) to replace 'x' to "X" for a particular column.
dataf["Type1"] = dataf["Type1"].replace({"Grass" : "GRASS","Fire":"FIRE"})

print(dataf.to_string())

      No        Name     Type1     Type2  Height  Weight
0      1   Bulbasaur     GRASS    Poison     0.7     6.9
1      1   Bulbasaur     GRASS    Poison     0.7     6.9
2      1   Bulbasaur     GRASS    Poison     0.7     6.9
3      1   Bulbasaur     GRASS    Poison     0.7     6.9
4      1   Bulbasaur     GRASS    Poison     0.7     6.9
5      2     Ivysaur     GRASS    Poison     1.0    13.0
6      3    Venusaur     GRASS    Poison     2.0   100.0
7      4  Charmander      FIRE      None     0.6     8.5
8      5  Charmeleon      FIRE      None     1.1    19.0
9      6   Charizard      FIRE    Flying     1.7    90.5
10     7    Squirtle     Water      None     0.5     9.0
11     8   Wartortle     Water      None     1.0    22.5
12     9   Blastoise     Water      None     1.6    85.5
13    10    Caterpie       Bug      None     0.3     2.9
14    11     Metapod       Bug      None     0.7     9.9
15    12  Butterfree       Bug    Flying     1.1    32.0
16    13      Weedle       Bug    Poison     0.3     3.2
17    14      Kakuna       Bug    Poison     0.6    10.0
18    15    Beedrill       Bug    Poison     1.0    29.5
19    16      Pidgey    Normal    Flying     0.3     1.8
20    17   Pidgeotto    Normal    Flying     1.1    30.0
21    18     Pidgeot    Normal    Flying     1.5    39.5
22    19     Rattata    Normal      None     0.3     3.5
23    20    Raticate    Normal      None     0.7    18.5
24    21     Spearow    Normal    Flying     0.3     2.0
25    22      Fearow    Normal    Flying     1.2    38.0
26    23       Ekans    Poison      None     2.0     6.9
27    24       Arbok    Poison      None     3.5    65.0
28    25     Pikachu  Electric      None     0.4     6.0
29    26      Raichu  Electric      None     0.8    30.0
30    27   Sandshrew    Ground      None     0.6    12.0
31    28   Sandslash    Ground      None     1.0    29.5
32    29    Nidoran♀    Poison      None     0.4     7.0
33    30    Nidorina    Poison      None     0.8    20.0
34    31   Nidoqueen    Poison    Ground     1.3    60.0
35    32    Nidoran♂    Poison      None     0.5     9.0
36    33    Nidorino    Poison      None     0.9    19.5
37    34    Nidoking    Poison    Ground     1.4    62.0
38    35    Clefairy     Fairy      None     0.6     7.5
39    36    Clefable     Fairy      None     1.3    40.0
40    37      Vulpix      FIRE      None     0.6     9.9
41    38   Ninetales      FIRE      None     1.1    19.9
42    39  Jigglypuff    Normal     Fairy     0.5     5.5
43    40  Wigglytuff    Normal     Fairy     1.0    12.0
44    41       Zubat    Poison    Flying     0.8     7.5
45    42      Golbat    Poison    Flying     1.6    55.0
46    43      Oddish     GRASS    Poison     0.5     5.4
47    44       Gloom     GRASS    Poison     0.8     8.6
48    45   Vileplume     GRASS    Poison     1.2    18.6
49    46       Paras       Bug     Grass     0.3     5.4
50    47    Parasect       Bug     Grass     1.0    29.5
51    48     Venonat       Bug    Poison     1.0    30.0
52    49    Venomoth       Bug    Poison     1.5    12.5
53    50     Diglett    Ground      None     0.2     0.8
54    51     Dugtrio    Ground      None     0.7    33.3
55    52      Meowth    Normal      None     0.4     4.2
56    53     Persian    Normal      None     1.0    32.0
57    54     Psyduck     Water      None     0.8    19.6
58    55     Golduck     Water      None     1.7    76.6
59    56      Mankey  Fighting      None     0.5    28.0
60    57    Primeape  Fighting      None     1.0    32.0
61    58   Growlithe      FIRE      None     0.7    19.0
62    59    Arcanine      FIRE      None     1.9   155.0
63    60     Poliwag     Water      None     0.6    12.4
64    61   Poliwhirl     Water      None     1.0    20.0
65    62   Poliwrath     Water  Fighting     1.3    54.0
66    63        Abra   Psychic      None     0.9    19.5
67    64     Kadabra   Psychic      None     1.3    56.5
68    65    Alakazam   Psychic      None     1.5    48.0
69    66      Machop  Fighting      None     0.8    19.5
70    67     Machoke  Fighting      None     1.5    70.5
71    68     Machamp  Fighting      None     1.6   130.0
72    69  Bellsprout     GRASS    Poison     0.7     4.0
73    70  Weepinbell     GRASS    Poison     1.0     6.4
74    71  Victreebel     GRASS    Poison     1.7    15.5
75    72   Tentacool     Water    Poison     0.9    45.5
76    73  Tentacruel     Water    Poison     1.6    55.0
77    74     Geodude      Rock    Ground     0.4    20.0
78    75    Graveler      Rock    Ground     1.0   105.0
79    76       Golem      Rock    Ground     1.4   300.0
80    77      Ponyta      FIRE      None     1.0    30.0
81    78    Rapidash      FIRE      None     1.7    95.0
82    79    Slowpoke     Water   Psychic     1.2    36.0
83    80     Slowbro     Water   Psychic     1.6    78.5
84    81   Magnemite  Electric     Steel     0.3     6.0
85    82    Magneton  Electric     Steel     1.0    60.0
86    83  Farfetch'd    Normal    Flying     0.8    15.0
87    84       Doduo    Normal    Flying     1.4    39.2
88    85      Dodrio    Normal    Flying     1.8    85.2
89    86        Seel     Water      None     1.1    90.0
90    87     Dewgong     Water       Ice     1.7   120.0
91    88      Grimer    Poison      None     0.9    30.0
92    89         Muk    Poison      None     1.2    30.0
93    90    Shellder     Water      None     0.3     4.0
94    91    Cloyster     Water       Ice     1.5   132.5
95    92      Gastly     Ghost    Poison     1.3     0.1
96    93     Haunter     Ghost    Poison     1.6     0.1
97    94      Gengar     Ghost    Poison     1.5    40.5
98    95        Onix      Rock    Ground     8.8   210.0
99    96     Drowzee   Psychic      None     1.0    32.4
100   97       Hypno   Psychic      None     1.6    75.6
101   98      Krabby     Water      None     0.4     6.5
102   99     Kingler     Water      None     1.3    60.0
103  100     Voltorb  Electric      None     0.5    10.4
104  101   Electrode  Electric      None     1.2    66.6
105  102   Exeggcute     GRASS   Psychic     0.4     2.5
106  103   Exeggutor     GRASS   Psychic     2.0   120.0
107  104      Cubone    Ground      None     0.4     6.5
108  105     Marowak    Ground      None     1.0    45.0
109  106   Hitmonlee  Fighting      None     1.5    49.8
110  107  Hitmonchan  Fighting      None     1.4    50.2
111  108   Lickitung    Normal      None     1.2    65.5
112  109     Koffing    Poison      None     0.6     1.0
113  110     Weezing    Poison      None     1.2     9.5
114  111     Rhyhorn    Ground      Rock     1.0   115.0
115  112      Rhydon    Ground      Rock     1.9   120.0
116  113     Chansey    Normal      None     1.1    34.6
117  114     Tangela     GRASS      None     1.0    35.0
118  115  Kangaskhan    Normal      None     2.2    80.0
119  116      Horsea     Water      None     0.4     8.0
120  117      Seadra     Water      None     1.2    25.0
121  118     Goldeen     Water      None     0.6    15.0
122  119     Seaking     Water      None     1.3    39.0
123  120      Staryu     Water      None     0.8    34.5
124  121     Starmie     Water   Psychic     1.1    80.0
125  122    Mr. Mime   Psychic     Fairy     1.3    54.5
126  123     Scyther       Bug    Flying     1.5    56.0
127  124        Jynx       Ice   Psychic     1.4    40.6
128  125  Electabuzz  Electric      None     1.1    30.0
129  126      Magmar      FIRE      None     1.3    44.5
130  127      Pinsir       Bug      None     1.5    55.0
131  128      Tauros    Normal      None     1.4    88.4
132  129    Magikarp     Water      None     0.9    10.0
133  130    Gyarados     Water    Flying     6.5   235.0
134  131      Lapras     Water       Ice     2.5   220.0
135  132       Ditto    Normal      None     0.3     4.0
136  133       Eevee    Normal      None     0.3     6.5
137  134    Vaporeon     Water      None     1.0    29.0
138  135     Jolteon  Electric      None     0.8    24.5
139  136     Flareon      FIRE      None     0.9    25.0
140  137     Porygon    Normal      None     0.8    36.5
141  138     Omanyte      Rock     Water     0.4     7.5
142  139     Omastar      Rock     Water     1.0    35.0
143  140      Kabuto      Rock     Water     0.5    11.5
144  141    Kabutops      Rock     Water     1.3    40.5
145  142  Aerodactyl      Rock    Flying     1.8    59.0
146  143     Snorlax    Normal      None     2.1   460.0
147  144    Articuno       Ice    Flying     1.7    55.4
148  145      Zapdos  Electric    Flying     1.6    52.6
149  146     Moltres      FIRE    Flying     2.0    60.0
150  147     Dratini    Dragon      None     1.8     3.3
151  148   Dragonair    Dragon      None     4.0    16.5
152  149   Dragonite    Dragon    Flying     2.2   210.0
153  150      Mewtwo   Psychic      None     2.0   122.0
154  150      Mewtwo   Psychic      None     2.0   122.0
155  150      Mewtwo   Psychic      None     2.0   122.0
156  150      Mewtwo   Psychic      None     2.0   122.0

In [38]:
# 4. Standardize text
dataf["Name"] = dataf["Name"].str.lower()

print(dataf.to_string())

      No        Name     Type1     Type2  Height  Weight
0      1   bulbasaur     GRASS    Poison     0.7     6.9
1      1   bulbasaur     GRASS    Poison     0.7     6.9
2      1   bulbasaur     GRASS    Poison     0.7     6.9
3      1   bulbasaur     GRASS    Poison     0.7     6.9
4      1   bulbasaur     GRASS    Poison     0.7     6.9
5      2     ivysaur     GRASS    Poison     1.0    13.0
6      3    venusaur     GRASS    Poison     2.0   100.0
7      4  charmander      FIRE      None     0.6     8.5
8      5  charmeleon      FIRE      None     1.1    19.0
9      6   charizard      FIRE    Flying     1.7    90.5
10     7    squirtle     Water      None     0.5     9.0
11     8   wartortle     Water      None     1.0    22.5
12     9   blastoise     Water      None     1.6    85.5
13    10    caterpie       Bug      None     0.3     2.9
14    11     metapod       Bug      None     0.7     9.9
15    12  butterfree       Bug    Flying     1.1    32.0
16    13      weedle       Bug    Poison     0.3     3.2
17    14      kakuna       Bug    Poison     0.6    10.0
18    15    beedrill       Bug    Poison     1.0    29.5
19    16      pidgey    Normal    Flying     0.3     1.8
20    17   pidgeotto    Normal    Flying     1.1    30.0
21    18     pidgeot    Normal    Flying     1.5    39.5
22    19     rattata    Normal      None     0.3     3.5
23    20    raticate    Normal      None     0.7    18.5
24    21     spearow    Normal    Flying     0.3     2.0
25    22      fearow    Normal    Flying     1.2    38.0
26    23       ekans    Poison      None     2.0     6.9
27    24       arbok    Poison      None     3.5    65.0
28    25     pikachu  Electric      None     0.4     6.0
29    26      raichu  Electric      None     0.8    30.0
30    27   sandshrew    Ground      None     0.6    12.0
31    28   sandslash    Ground      None     1.0    29.5
32    29    nidoran♀    Poison      None     0.4     7.0
33    30    nidorina    Poison      None     0.8    20.0
34    31   nidoqueen    Poison    Ground     1.3    60.0
35    32    nidoran♂    Poison      None     0.5     9.0
36    33    nidorino    Poison      None     0.9    19.5
37    34    nidoking    Poison    Ground     1.4    62.0
38    35    clefairy     Fairy      None     0.6     7.5
39    36    clefable     Fairy      None     1.3    40.0
40    37      vulpix      FIRE      None     0.6     9.9
41    38   ninetales      FIRE      None     1.1    19.9
42    39  jigglypuff    Normal     Fairy     0.5     5.5
43    40  wigglytuff    Normal     Fairy     1.0    12.0
44    41       zubat    Poison    Flying     0.8     7.5
45    42      golbat    Poison    Flying     1.6    55.0
46    43      oddish     GRASS    Poison     0.5     5.4
47    44       gloom     GRASS    Poison     0.8     8.6
48    45   vileplume     GRASS    Poison     1.2    18.6
49    46       paras       Bug     Grass     0.3     5.4
50    47    parasect       Bug     Grass     1.0    29.5
51    48     venonat       Bug    Poison     1.0    30.0
52    49    venomoth       Bug    Poison     1.5    12.5
53    50     diglett    Ground      None     0.2     0.8
54    51     dugtrio    Ground      None     0.7    33.3
55    52      meowth    Normal      None     0.4     4.2
56    53     persian    Normal      None     1.0    32.0
57    54     psyduck     Water      None     0.8    19.6
58    55     golduck     Water      None     1.7    76.6
59    56      mankey  Fighting      None     0.5    28.0
60    57    primeape  Fighting      None     1.0    32.0
61    58   growlithe      FIRE      None     0.7    19.0
62    59    arcanine      FIRE      None     1.9   155.0
63    60     poliwag     Water      None     0.6    12.4
64    61   poliwhirl     Water      None     1.0    20.0
65    62   poliwrath     Water  Fighting     1.3    54.0
66    63        abra   Psychic      None     0.9    19.5
67    64     kadabra   Psychic      None     1.3    56.5
68    65    alakazam   Psychic      None     1.5    48.0
69    66      machop  Fighting      None     0.8    19.5
70    67     machoke  Fighting      None     1.5    70.5
71    68     machamp  Fighting      None     1.6   130.0
72    69  bellsprout     GRASS    Poison     0.7     4.0
73    70  weepinbell     GRASS    Poison     1.0     6.4
74    71  victreebel     GRASS    Poison     1.7    15.5
75    72   tentacool     Water    Poison     0.9    45.5
76    73  tentacruel     Water    Poison     1.6    55.0
77    74     geodude      Rock    Ground     0.4    20.0
78    75    graveler      Rock    Ground     1.0   105.0
79    76       golem      Rock    Ground     1.4   300.0
80    77      ponyta      FIRE      None     1.0    30.0
81    78    rapidash      FIRE      None     1.7    95.0
82    79    slowpoke     Water   Psychic     1.2    36.0
83    80     slowbro     Water   Psychic     1.6    78.5
84    81   magnemite  Electric     Steel     0.3     6.0
85    82    magneton  Electric     Steel     1.0    60.0
86    83  farfetch'd    Normal    Flying     0.8    15.0
87    84       doduo    Normal    Flying     1.4    39.2
88    85      dodrio    Normal    Flying     1.8    85.2
89    86        seel     Water      None     1.1    90.0
90    87     dewgong     Water       Ice     1.7   120.0
91    88      grimer    Poison      None     0.9    30.0
92    89         muk    Poison      None     1.2    30.0
93    90    shellder     Water      None     0.3     4.0
94    91    cloyster     Water       Ice     1.5   132.5
95    92      gastly     Ghost    Poison     1.3     0.1
96    93     haunter     Ghost    Poison     1.6     0.1
97    94      gengar     Ghost    Poison     1.5    40.5
98    95        onix      Rock    Ground     8.8   210.0
99    96     drowzee   Psychic      None     1.0    32.4
100   97       hypno   Psychic      None     1.6    75.6
101   98      krabby     Water      None     0.4     6.5
102   99     kingler     Water      None     1.3    60.0
103  100     voltorb  Electric      None     0.5    10.4
104  101   electrode  Electric      None     1.2    66.6
105  102   exeggcute     GRASS   Psychic     0.4     2.5
106  103   exeggutor     GRASS   Psychic     2.0   120.0
107  104      cubone    Ground      None     0.4     6.5
108  105     marowak    Ground      None     1.0    45.0
109  106   hitmonlee  Fighting      None     1.5    49.8
110  107  hitmonchan  Fighting      None     1.4    50.2
111  108   lickitung    Normal      None     1.2    65.5
112  109     koffing    Poison      None     0.6     1.0
113  110     weezing    Poison      None     1.2     9.5
114  111     rhyhorn    Ground      Rock     1.0   115.0
115  112      rhydon    Ground      Rock     1.9   120.0
116  113     chansey    Normal      None     1.1    34.6
117  114     tangela     GRASS      None     1.0    35.0
118  115  kangaskhan    Normal      None     2.2    80.0
119  116      horsea     Water      None     0.4     8.0
120  117      seadra     Water      None     1.2    25.0
121  118     goldeen     Water      None     0.6    15.0
122  119     seaking     Water      None     1.3    39.0
123  120      staryu     Water      None     0.8    34.5
124  121     starmie     Water   Psychic     1.1    80.0
125  122    mr. mime   Psychic     Fairy     1.3    54.5
126  123     scyther       Bug    Flying     1.5    56.0
127  124        jynx       Ice   Psychic     1.4    40.6
128  125  electabuzz  Electric      None     1.1    30.0
129  126      magmar      FIRE      None     1.3    44.5
130  127      pinsir       Bug      None     1.5    55.0
131  128      tauros    Normal      None     1.4    88.4
132  129    magikarp     Water      None     0.9    10.0
133  130    gyarados     Water    Flying     6.5   235.0
134  131      lapras     Water       Ice     2.5   220.0
135  132       ditto    Normal      None     0.3     4.0
136  133       eevee    Normal      None     0.3     6.5
137  134    vaporeon     Water      None     1.0    29.0
138  135     jolteon  Electric      None     0.8    24.5
139  136     flareon      FIRE      None     0.9    25.0
140  137     porygon    Normal      None     0.8    36.5
141  138     omanyte      Rock     Water     0.4     7.5
142  139     omastar      Rock     Water     1.0    35.0
143  140      kabuto      Rock     Water     0.5    11.5
144  141    kabutops      Rock     Water     1.3    40.5
145  142  aerodactyl      Rock    Flying     1.8    59.0
146  143     snorlax    Normal      None     2.1   460.0
147  144    articuno       Ice    Flying     1.7    55.4
148  145      zapdos  Electric    Flying     1.6    52.6
149  146     moltres      FIRE    Flying     2.0    60.0
150  147     dratini    Dragon      None     1.8     3.3
151  148   dragonair    Dragon      None     4.0    16.5
152  149   dragonite    Dragon    Flying     2.2   210.0
153  150      mewtwo   Psychic      None     2.0   122.0
154  150      mewtwo   Psychic      None     2.0   122.0
155  150      mewtwo   Psychic      None     2.0   122.0
156  150      mewtwo   Psychic      None     2.0   122.0

In [39]:
# 5. Fix Data types
dt = pd.read_csv("pokemon.csv")

dt["Legendary"] = dt["Legendary"].astype(bool)
dt

      No       Name    Type1   Type2  Height  Weight  Legendary
0      1  Bulbasaur    Grass  Poison     0.7     6.9      False
1      1  Bulbasaur    Grass  Poison     0.7     6.9      False
2      1  Bulbasaur    Grass  Poison     0.7     6.9      False
3      1  Bulbasaur    Grass  Poison     0.7     6.9      False
4      1  Bulbasaur    Grass  Poison     0.7     6.9      False
..   ...        ...      ...     ...     ...     ...        ...
152  149  Dragonite   Dragon  Flying     2.2   210.0      False
153  150     Mewtwo  Psychic     NaN     2.0   122.0       True
154  150     Mewtwo  Psychic     NaN     2.0   122.0       True
155  150     Mewtwo  Psychic     NaN     2.0   122.0       True
156  150     Mewtwo  Psychic     NaN     2.0   122.0       True

[157 rows x 7 columns]

In [40]:
# 6. Remove Duplicate Values
dt = dt.drop_duplicates()
dt

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9      False
5      2     Ivysaur    Grass  Poison     1.0    13.0      False
6      3    Venusaur    Grass  Poison     2.0   100.0      False
7      4  Charmander     Fire     NaN     0.6     8.5      False
8      5  Charmeleon     Fire     NaN     1.1    19.0      False
..   ...         ...      ...     ...     ...     ...        ...
149  146     Moltres     Fire  Flying     2.0    60.0       True
150  147     Dratini   Dragon     NaN     1.8     3.3      False
151  148   Dragonair   Dragon     NaN     4.0    16.5      False
152  149   Dragonite   Dragon  Flying     2.2   210.0      False
153  150      Mewtwo  Psychic     NaN     2.0   122.0       True

[150 rows x 7 columns]